### ISSUE TITLE
Unity: Probe Batch component fails when SteamAudioStaticMesh component is not in root game object

### ISSUE THREAD

**Issue by Level3Manatee** [ValveSoftware/steam-audio#183]
Steam Audio Unity v4.0.3
Unity 2021.2.6f1
FMOD 2.02.05

Using `Steam Audio > Export Active Scene` will update the scene asset reference even when the `SteamAudioStaticMesh` is on a non-root game object, while the `SteamAudioProbeBatch` component will only look for it on root-level game objects.

As a result, the Probe Batch component can fail to generate probes, error message "Scene [...] has not been exported.", even when the scene is exported successfully, leading to confusion.

The export function should either warn about non-root instances, or the `SteamAudioProbeBatch` should look for the component recursively.

Background: I set up my first scene with Steam Audio and erroneously added the `SteamAudioStaticMesh` component to static geometry, assuming it was the static equivalent to `SteamAudioGeometry`. After reading the documentation on the Geometry component, I removed the `SteamAudioStaticMesh` components, as the docs stated it assumed static geometry by default. This left me confused about the use of the `SteamAudioStaticMesh` component. Only after specifically looking up the component documentation I realized my mistake. The probe batch component did not work for me even after this, because I apparently forgot to remove the static mesh component on one of my meshes. I could export the scene without errors, while the probe batch could not find it afterwards.

It might also be worth considering renaming the `SteamAudioStaticMesh` component to something containing the word 'scene' to make the name less ambiguous.

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0. This release contains a fix for this issue.

**Comment by owlboy** [comment]
This issue still occurs for me in v4.1.2 with `SteamAudioProbeBatch` and a `SteamAudioStaticMesh` not in the root of the hierarchy.
