### ISSUE TITLE
DSP parameter indexes are not exposed

### ISSUE THREAD

**Issue by melody-rs** [ValveSoftware/steam-audio#432]
https://github.com/ValveSoftware/steam-audio/blob/d747565385a0a771f820f97f870ddc7cd0d21db2/fmod/src/spatialize_effect.cpp#L34-L393
https://github.com/ValveSoftware/steam-audio/blob/d747565385a0a771f820f97f870ddc7cd0d21db2/fmod/src/reverb_effect.cpp#L26-L51
https://github.com/ValveSoftware/steam-audio/blob/d747565385a0a771f820f97f870ddc7cd0d21db2/fmod/src/mix_return_effect.cpp#L26-L51

These parameter enums aren't defined outside of their source `cpp` file, so they don't show up in doxygen:

![Image](https://github.com/user-attachments/assets/aea6a12e-d87e-4961-9fa1-5192192a5a78)

In order to properly use SteamAudio's FMOD integration you have to set DSP parameters. Because SteamAudio doesn't expose its parameter indexes, they have to be hardcoded.
Even the Unity plugin does this:
https://github.com/ValveSoftware/steam-audio/blob/d747565385a0a771f820f97f870ddc7cd0d21db2/unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/FMODStudio/FMODStudioAudioEngineSource.cs#L33

Currently to get the parameter indexes you either have to dig through the SteamAudio source code or use `FMOD::DSP::getParameterInfo`

**Comment by lakulish** [comment]
@melody-rs Thanks for pointing this out, I've committed a fix for the issue. You can build the docs locally to see the fixed version, until the docs on the website are updated.

**Comment by melody-rs** [comment]
@lakulish That might've fixed the documentation, but that doesn't fix the issue of having to hardcode parameter indexes. They should be defined inside `steamaudio_fmod.h` as well, like FMOD does:
https://github.com/ValveSoftware/steam-audio/blob/d747565385a0a771f820f97f870ddc7cd0d21db2/fmod/include/fmod/fmod_dsp_effects.h#L342-L368

Also, open source distribution of the FMOD headers might not be allowed:
https://qa.fmod.com/t/distributing-fmod-headers/21708/5
