### ISSUE TITLE
[UE4] Phonon Probe Volume and Phonon Geometry not working on Instanced Static Meshes

### ISSUE THREAD

**Issue by Badtz52** [ValveSoftware/steam-audio#64]

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes an updated Unreal Engine plugin: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

Try it out and let us know if you continue to face issues in the new version.

**Comment by manuel5975p** [comment]
Hello
Instanced static meshes are still not supported I believe.
